# SPDX-FileCopyrightText: 2026 Joel Winarske
# SPDX-License-Identifier: MIT

name: ihs_webrtc_view_example
description: "Runs a decoded WebRTC video track in a WebRtcView on ivi-homescreen."
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  ihs_webrtc_view:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
